POST http://localhost:8000/users/signup HTTP/1.1
content-type: application/json

{
    "first_name":"Bhargav",
    "last_name":"Reddy",
    "email":"bhagi1224@gmail.com",
    "password":"123456",
    "confirm_password":"123456",
}

###

GET http://localhost:8000/users/signup HTTP/1.1

###

POST http://localhost:8000/users/signin HTTP/1.1
content-type: application/json

{
    "email":"bhagi1224@gmail.com",
    "password":"123456",
}